name: Development

on:
  push:
    branches: [ dev ]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    # Initialize
    - uses: actions/checkout@v2
    # Java setup
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Run tests
      run: mvn -B test --file pom.xml
    
    - name: Run build
      run: mvn -B build --file pom.xml
  
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: sigfriedseldeslachts/app:dev
    
    
